apiVersion: apps/v1
kind: Deployment
metadata: 
  name: remote-msa
  labels:
    app: remote-msa
spec:
  replicas: 3 # three pod
  selector:
    matchLabels:
      app: remote-msa
  template:
    metadata:
      labels:
        app: remote-msa
    spec:
      containers:
      - name: remote-msa
        image: gamgammoo/remote-msa
        ports:
        - containerPort: 8000 # container port (pod port)
