#base image
FROM ubuntu:16.04

# Nginx install
RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get -y install nginx
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

# port setup
EXPOSE 80

# Web content allocation
ONBUILD ADD website.tar /var/www/html/

# Nginx execution
CMD ["nginx"]
