name: tetris
version: 0.1.0.0
author: Attila Domokos <adomokos@gmail.com>
maintainer: adomokos@gmail.com
copyright: 2018 Attila Domokos
category: Console App
homepage: https://github.com/adomokos/tetris#readme

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - split
  - containers

library:
  source-dirs: src/
  exposed-modules:
    - Tetris.Logic

executables:
  tetris-exe:
    source-dirs: app/
    main: Main.hs
    dependencies:
      tetris
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  tetris-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - tetris
      - hspec == 2.*
      - QuickCheck
