#base images
From ubuntu:latest

#run command
Run echo Hello~ It is shell type command.
RUN ["echo", "Hello~ It is exec type command."]
RUN ["/bin/bash","-c","echo 'Hello~ It is /bin/bash execution in shell type command.'"]
